export const GDPT_2018_SUBJECTS = [
  "Tiếng Việt",
  "Ngữ văn",
  "Toán",
  "Tiếng Anh",
  "Ngoại ngữ 1",
  "Đạo đức",
  "Giáo dục công dân",
  "Giáo dục kinh tế và pháp luật",
  "Tự nhiên và Xã hội",
  "Khoa học",
  "Khoa học tự nhiên",
  "Lịch sử và Địa lí",
  "Lịch sử",
  "Địa lí",
  "Vật lí",
  "Hoá học",
  "Sinh học",
  "Tin học",
  "Công nghệ",
  "Giáo dục thể chất",
  "Âm nhạc",
  "Mĩ thuật",
  "Hoạt động trải nghiệm, hướng nghiệp",
  "Nội dung giáo dục địa phương",
  "Giáo dục quốc phòng và an ninh",
  "Chuyên đề học tập"
];
