export const GDPT_2018_SUBJECTS = [
  "Toán học",
  "Toán",
  "Ngữ văn",
  "Tiếng Việt",
  "Tiếng Anh",
  "Ngoại ngữ 1",
  "Vật lí",
  "Hóa học",
  "Hoá học",
  "Sinh học",
  "Khoa học tự nhiên",
  "Lịch sử",
  "Địa lí",
  "Lịch sử và Địa lí",
  "Giáo dục công dân",
  "Giáo dục kinh tế và pháp luật",
  "Tin học",
  "Công nghệ",
  "Tự nhiên và Xã hội",
  "Khoa học",
  "Đạo đức",
  "Hoạt động trải nghiệm, hướng nghiệp",
  "Hoạt động trải nghiệm",
  "Nội dung giáo dục địa phương",
  "Giáo dục quốc phòng và an ninh",
  "Giáo dục thể chất",
  "Âm nhạc",
  "Mĩ thuật",
  "Chuyên đề học tập"
];

